# Generated by Django 5.1.1 on 2024-09-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_userresponse_options_alter_message_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Герой', 'verbose_name_plural': 'Герои'},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание героя'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.message'),
        ),
    ]
