# Generated by Django 5.1.1 on 2024-09-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=1, verbose_name='Описание героя'),
            preserve_default=False,
        ),
    ]
