# Generated by Django 5.1.1 on 2024-09-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_userresponse_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.message', verbose_name='Мой герой'),
            preserve_default=False,
        ),
    ]
